language: java
jdk:
  - openjdk11
branches:
  only:
    - master
before_install:
  - 'curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"'
  - 'unzip awscli-bundle.zip'
  - './awscli-bundle/install -b ~/bin/aws'
  - 'export PATH=~/bin:$PATH'
install: echo "here"
script: ./plus-f/release.sh
