version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: alangibson27/jdk11-with-awscli
    steps:
      - add_ssh_keys:
          fingerprints:
            - "5c:3c:f5:6b:70:81:12:7b:db:e5:8d:ba:1c:38:5e:c4"
      - checkout
      - run: git config --global user.email "alangibson27@gmail.com"
      - run: git config --global user.name "Alan Gibson (via CircleCI)"
      - run: AWS_CMD=~/bin/aws plus-f/build.sh
